

name: Master - Docker Build/Publish README

on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_REPOSITORY: assistantprojectalice/main-unit
