name: Master - OS Build/Publish Image

on:
  push:
    branches: [ master ]
    paths:
      - 'base-os-docker/**'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-os-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-os-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: wraithrmm
          password: e3c4c81a-3c40-4588-b6b8-41899013a41d
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./base-os-docker/
          file: ./base-os-docker/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: wraithrmm/alice-base-os:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
